### ISSUE TITLE
html内容解析丢失的bad casse

### ISSUE THREAD

**Issue by uuid1017** [ant-mini-program/mini-html-parser#5]
下面的内容包含文案的，但是最终解析之后只有一个图片，文案被吃掉了
使用版本：0.2.0

`"<div style=\"clear: both;\"><div class=\"bq-header\" style=\"margin: 4px 0px; padding: 0px; color: rgba(0, 0, 0, 0.65); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; text-align: center; text-indent: 0px; text-transform: none; text-decoration-style: initial; text-decoration-color: initial;\"><h1 style=\"margin: 0px; padding: 0px; font-size: 30px;\"><br></h1></div><div class=\"bq-content\" style=\"margin: 0px; padding: 0px; color: rgba(0, 0, 0, 0.65); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; text-align: center; text-indent: 0px; text-transform: none; text-decoration-style: initial; text-decoration-color: initial;\"><img src=\"https://img.alicdn.com/tfs/TB1P0p.uQY2gK0jSZFgXXc5OFXa-260-260.png\" alt=\"\" class=\"bq-qrcode\" style=\"margin: 0px 0px 10px; padding: 0px; vertical-align: bottom;\"><p style=\"margin: 0px 0px 10px; padding: 0px;\">请打开【<span>&nbsp;</span><img src=\"https://img.alicdn.com/tfs/TB19WeauQT2gK0jSZPcXXcKkpXa-62-57.png\" alt=\"\" class=\"bq-logo\" style=\"margin: 0px; padding: 0px; vertical-align: middle; width: 30px; height: 30px;\"><span>&nbsp;</span>浙里办 APP】首页右上角<span>&nbsp;</span><img src=\"https://img.alicdn.com/tfs/TB1uxmauHj1gK0jSZFOXXc7GpXa-2000-2000.png\" alt=\"\" class=\"bq-scan\" style=\"margin: 0px; padding: 0px; vertical-align: middle; width: 40px; height: 40px;\"><span>&nbsp;</span>使用</p></div></div>"`

**Comment by pingan1927** [comment]
0.3.0版本应该修复了此问题。
